name: main

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Prettier check
        run: npm run prettier --check "**/*.{js,jsx,ts,tsx,json,md}"

  deploy:
    if: github.ref == 'refs/heads/main'
    name: Gatsby Publish
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Github Pages
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm run deploy
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
